import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFEF9',
    },
    safeArea: {
        flex: 1,
    },
    header: {
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        height: 60,
    },
    logoContainer: {
        width: 80,
    },
    logo: {
        width: 70,
        height: 28,
    },
    rightIcons: {
        justifyContent: 'flex-end',
    },
    iconsIslandContent: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 20,
        paddingHorizontal: 5,
        paddingVertical: 5,
        gap: 8,
    },
    shieldContainer: {
        width: 26,
        height: 26,
        borderRadius: 13,
        justifyContent: 'center',
        alignItems: 'center',
    },
    shieldCountText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#111111',
    },
    dateIslandCentered: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 12,
        bottom: 16,
        justifyContent: 'center',
        alignItems: 'center',
        pointerEvents: 'box-none',
    },
    dateIslandContent: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 20,
        paddingHorizontal: 5,
        paddingVertical: 5,
        gap: 8,
    },
    dateArrowButton: {
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    dateText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#111111',
        minWidth: 50,
        textAlign: 'center',
    },
    bottomDockContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        alignItems: 'center',
        paddingBottom: 34,
    },
    bottomDockPill: {
        width: width * 0.9,
        height: 68,
        backgroundColor: '#FFFFFF',
        borderRadius: 34,
        borderWidth: 1,
        borderColor: '#E5E5E5',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
        elevation: 8,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    dailyScoreModule: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    scoreBadge: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: '#F8EBE6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    scoreTextContainer: {
        justifyContent: 'center',
    },
    scoreLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#7B8B9B',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
        marginBottom: 2,
    },
    scoreNumberContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
    },
    scoreNumber: {
        fontSize: 20,
        fontWeight: '700',
        color: '#343A40',
    },
    scoreTotal: {
        fontSize: 13.5,
        fontWeight: '500',
        color: '#7B8B9B',
        opacity: 0.55,
        marginLeft: 6,
    },
    dockIconsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginLeft: 'auto',
    },
    dockIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F5F5F5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    dockIconImage: {
        width: 20,
        height: 20,
    },
    dropdownContainer: {
        position: 'absolute',
        bottom: 112, // Final adjusted position above the dock pill
        right: 20,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 8,
        width: 180,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 10,
        zIndex: 1000,
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 8,
    },
    dropdownText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#111111',
        marginLeft: 12,
    },
    dropdownOverlay: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 999,
    },
});
